library(reshape)
library(RColorBrewer)
library(ggplot2)
library(plyr)
# This file does some basic diagnostics on MSA level ad price information
source('R-Estout2/eststo2.R')
source('R-Estout2/esttab2.R')
source('R-Estout2/estclear.R')
#sink('results/micro_zero_price/zero_price_diagnostics.txt')
#data<-read.csv('results/micro_zero_price/zero_price_msa_aggregates.csv')
data<-read.csv('ad_prices_msa_micro.csv')
#data<-read.csv('ad_prices_msa.csv')
data<-data[data$zero_price_count > 50,]
data<-data[!is.na(data$mp_p75),]
cat('reading ad_prices_msa.csv...\n')
print(summary(data))

### Begin doing 5 different output quantiles
estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_50.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_50.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_50.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_50.txt'))

estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_25.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_25.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_25.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_25.txt'))

estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_75.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_75.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_75.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_75.txt'))

estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_75_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_75_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_75_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_75_nv.txt'))

estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_25_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_25_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_25_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_25_nv.txt'))

estclear()
eststo2(lm(zp_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(zp_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(zp_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(zp_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_50_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/zero_price_by_quantile_50_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/zero_price_by_quantile_50_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/zero_price_by_quantile_50_nv.txt'))

### End zero price by quantiles

### Begin ad price by quantiles
estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_50.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_50.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_50.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_50.txt'))

estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_25.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_25.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_25.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_25.txt'))

estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_75.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_75.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_75.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_75.txt'))

estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_75_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_75_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_75_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_75_nv.txt'))

estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_25_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_25_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_25_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_25_nv.txt'))

estclear()
eststo2(lm(ad_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(ad_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(ad_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(ad_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_50_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/hourly_price_by_quantile_50_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/hourly_price_by_quantile_50_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/hourly_price_by_quantile_50_nv.txt'))
# End hourly price quantiles

# Begin marginal price quantiles
estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_50.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_50.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_50.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_50.txt'))

estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_25.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_25.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_25.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_25.txt'))

estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_75.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_75.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_75.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_75.txt'))

estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p75 + male_wage_p75 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_75_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_75_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_75_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_75_nv.txt'))

estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p25 + male_wage_p25 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_25_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_25_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_25_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_25_nv.txt'))

estclear()
eststo2(lm(mp_p10 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(mp_p25 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(mp_p75 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
eststo2(lm(mp_p90 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop, data = data))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_50_nv.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='results/micro_zero_price/marginal_price_by_quantile_50_nv.txt', col.headers=c("p10","p25","p50","p75","p90"))
cat('______________\n')
cat('results/micro_zero_price/marginal_price_by_quantile_50_nv.txt:\n')
writeLines(readLines('results/micro_zero_price/marginal_price_by_quantile_50_nv.txt'))

# Begin exploring Xs
estclear()
eststo2(lm(mp_p50 ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(mp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/mp_explore.csv')
esttab2(filename='results/micro_zero_price/mp_explore.txt')

estclear()
eststo2(lm(zp_p50 ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zp_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/zp_explore.csv')
esttab2(filename='results/micro_zero_price/zp_explore.txt')

estclear()
eststo2(lm(ad_p50 ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(ad_p50 ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/1hour_explore.csv')
esttab2(filename='results/micro_zero_price/1hour_explore.txt')

