library(reshape)
library(RColorBrewer)
library(ggplot2)
library(plyr)
# This file does some basic diagnostics on MSA level ad price information
source('R-Estout2/eststo2.R')
source('R-Estout2/esttab2.R')
source('R-Estout2/estclear.R')
#sink('results/micro_zero_price/zero_price_diagnostics.txt')
#data<-read.csv('results/micro_zero_price/zero_price_msa_aggregates.csv')
data<-read.csv('ad_prices_msa_micro.csv')
#data<-read.csv('ad_prices_msa.csv')
data<-data[data$zero_price_count > 50,]
#data<-data[!is.na(data$mp_p75),]
cat('reading ad_prices_msa_micro.csv...\n')
print(summary(data))

# Begin exploring Xs
estclear()
eststo2(lm(marginal_price ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(marginal_price ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/mp_explore.csv')
esttab2(filename='results/micro_zero_price/mp_explore.txt')
cat('______________\n')
cat('results/micro_zero_price/mp_explore.txt:\n')
writeLines(readLines('results/micro_zero_price/mp_explore.txt'))

estclear()
eststo2(lm(zero_price ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(zero_price ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/zp_explore.csv')
esttab2(filename='results/micro_zero_price/zp_explore.txt')
cat('______________\n')
cat('results/micro_zero_price/zp_explore.txt:\n')
writeLines(readLines('results/micro_zero_price/zp_explore.txt'))


estclear()
eststo2(lm(price_per_hour ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = data))
esttab2(filename='results/micro_zero_price/1hour_explore.csv')
esttab2(filename='results/micro_zero_price/1hour_explore.txt')
cat('______________\n')
cat('results/micro_zero_price/1hour_explore.txt:\n')
writeLines(readLines('results/micro_zero_price/1hour_explore.txt'))

sub<-data[!is.na(data$marginal_price),]
estclear()
eststo2(lm(price_per_hour ~ avg_commute + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + female_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + male_wage_p50 + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
eststo2(lm(price_per_hour ~ avg_commute + female_wage_p50 + male_wage_p50 + female_epop + male_epop + rape_per_capita + property_crime_per_capita + le_per_capita, data = sub))
esttab2(filename='results/micro_zero_price/1hour_explore_sub.csv')
esttab2(filename='results/micro_zero_price/1hour_explore_sub.txt')
cat('______________\n')
cat('results/micro_zero_price/1hour_explore_sub.txt:\n')
writeLines(readLines('results/micro_zero_price/1hour_explore_sub.txt'))


