library(reshape)
library(RColorBrewer)
library(ggplot2)
library(plyr)
# This file does some basic diagnostics on MSA level ad price information
source('R-Estout2/eststo2.R')
source('R-Estout2/esttab2.R')
source('R-Estout2/estclear.R')
#sink('zero_price_diagnostics.txt')
data<-read.csv('zero_price_msa_aggregates.csv')
data$violence_per_capita<-data$violence_counts/data$population
data$female_violence_share<-data$female_violence_fraction/data$violence_fraction
cat('reading zero_price_msa_aggregates.csv...\n')
print(summary(data))
estclear()
eststo2(lm(zp_mean ~ female_violence_share, data=data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_mean.csv')
esttab2(filename='zero_price_msa_diagnostics_mean.txt')
writeLines(readLines('zero_price_msa_diagnostics_mean.txt'))

estclear()
eststo2(lm(zp_p90 ~ female_violence_share, data=data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_p90.csv')
esttab2(filename='zero_price_msa_diagnostics_p90.txt')
writeLines(readLines('zero_price_msa_diagnostics_p90.txt'))

estclear()
eststo2(lm(zp_p10 ~ female_violence_share, data=data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_p10.csv')
esttab2(filename='zero_price_msa_diagnostics_p10.txt')
writeLines(readLines('zero_price_msa_diagnostics_p10.txt'))


