library(reshape)
library(RColorBrewer)
library(ggplot2)
library(plyr)
# This file does some basic diagnostics on MSA level ad price information
source('R-Estout2/eststo2.R')
source('R-Estout2/esttab2.R')
source('R-Estout2/estclear.R')
#sink('zero_price_diagnostics.txt')
data<-read.csv('zero_price_msa_aggregates.csv')
data$violence_per_capita<-data$violence_counts/data$population
data$female_violence_share<-data$female_violence_fraction/data$violence_fraction
data$female_num_jobs<-data$female_sum.wght/1000
data$male_num_jobs<-data$male_sum.wght/1000
cat('reading zero_price_msa_aggregates.csv...\n')
print(summary(data))
estclear()
eststo2(lm(zp_mean ~ female_violence_share, data=data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_mean ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_mean.csv')
esttab2(filename='zero_price_msa_diagnostics_mean.txt')
writeLines(readLines('zero_price_msa_diagnostics_mean.txt'))

estclear()
eststo2(lm(zp_p90 ~ female_violence_share, data=data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_p90.csv')
esttab2(filename='zero_price_msa_diagnostics_p90.txt')
writeLines(readLines('zero_price_msa_diagnostics_p90.txt'))

estclear()
eststo2(lm(zp_p10 ~ female_violence_share, data=data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50) + female_violence_share, data = data))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute, data=data[!is.na(data$female_violence_share),]))
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + log(female_p50) + log(male_p50), data = data[!is.na(data$female_violence_share),]))
esttab2(filename='zero_price_msa_diagnostics_p10.csv')
esttab2(filename='zero_price_msa_diagnostics_p10.txt')
writeLines(readLines('zero_price_msa_diagnostics_p10.txt'))

estclear()
eststo2(lm(zp_p10 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + male_p25 + male_p50 + male_p75 + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p25 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + male_p25 + male_p50 + male_p75 + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p50 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + male_p25 + male_p50 + male_p75 + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p75 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + male_p25 + male_p50 + male_p75 + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + lt_highschool + highschool + college_plus + avg_commute + male_p25 + male_p50 + male_p75 + female_violence_share + violence_per_capita, data = data))
esttab2(filename='zero_price_by_quantile_male_quantiles.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='zero_price_by_quantile_male_quantiles.txt', col.headers=c("p10","p25","p50","p75","p90"))
writeLines(readLines('zero_price_by_quantile_male_quantiles.txt'))

estclear()
eststo2(lm(zp_p10 ~ log(population) + unemployment + avg_commute + female_p25 + female_p50 + female_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p25 ~ log(population) + unemployment + avg_commute + female_p25 + female_p50 + female_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p50 ~ log(population) + unemployment + avg_commute + female_p25 + female_p50 + female_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p75 ~ log(population) + unemployment + avg_commute + female_p25 + female_p50 + female_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + avg_commute + female_p25 + female_p50 + female_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
esttab2(filename='zero_price_by_quantile_female_quantiles.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='zero_price_by_quantile_female_quantiles.txt', col.headers=c("p10","p25","p50","p75","p90"))
writeLines(readLines('zero_price_by_quantile_female_quantiles.txt'))

estclear()
eststo2(lm(zp_p10 ~ log(population) + unemployment + avg_commute + female_p50 + male_p50 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p25 ~ log(population) + unemployment + avg_commute + female_p50 + male_p50 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p50 ~ log(population) + unemployment + avg_commute + female_p50 + male_p50 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p75 ~ log(population) + unemployment + avg_commute + female_p50 + male_p50 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + avg_commute + female_p50 + male_p50 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
esttab2(filename='zero_price_by_quantile_50.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='zero_price_by_quantile_50.txt', col.headers=c("p10","p25","p50","p75","p90"))
writeLines(readLines('zero_price_by_quantile_50.txt'))

estclear()
eststo2(lm(zp_p10 ~ log(population) + unemployment + avg_commute + female_p25 + male_p25 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p25 ~ log(population) + unemployment + avg_commute + female_p25 + male_p25 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p50 ~ log(population) + unemployment + avg_commute + female_p25 + male_p25 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p75 ~ log(population) + unemployment + avg_commute + female_p25 + male_p25 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + avg_commute + female_p25 + male_p25 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
esttab2(filename='zero_price_by_quantile_25.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='zero_price_by_quantile_25.txt', col.headers=c("p10","p25","p50","p75","p90"))
writeLines(readLines('zero_price_by_quantile_25.txt'))

estclear()
eststo2(lm(zp_p10 ~ log(population) + unemployment + avg_commute + female_p75 + male_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p25 ~ log(population) + unemployment + avg_commute + female_p75 + male_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p50 ~ log(population) + unemployment + avg_commute + female_p75 + male_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p75 ~ log(population) + unemployment + avg_commute + female_p75 + male_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
eststo2(lm(zp_p90 ~ log(population) + unemployment + avg_commute + female_p75 + male_p75 + female_num_jobs + male_num_jobs + female_violence_share + violence_per_capita, data = data))
esttab2(filename='zero_price_by_quantile_75.csv', col.headers=c("p10","p25","p50","p75","p90"))
esttab2(filename='zero_price_by_quantile_75.txt', col.headers=c("p10","p25","p50","p75","p90"))
writeLines(readLines('zero_price_by_quantile_75.txt'))


